# Generated by Django 2.0.4 on 2018-04-17 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('int', 'int'), ('string', 'string'), ('boolean', 'boolean'), ('float', 'float')], max_length=20)),
                ('value', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestApiTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=2000)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('OPTION', 'OPTION')], max_length=20)),
                ('data_type', models.CharField(default='json', max_length=200)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('successed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=True, to='apimanager.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Validate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200)),
                ('comparator', models.CharField(choices=[('eq', 'eq'), ('exists', 'exists')], max_length=20)),
                ('data_type', models.CharField(choices=[('int', 'int'), ('string', 'string'), ('boolean', 'boolean'), ('float', 'float')], max_length=20)),
                ('expected', models.CharField(max_length=2000)),
                ('tc', models.ForeignKey(on_delete=True, to='apimanager.RestApiTestCase')),
            ],
        ),
        migrations.AddField(
            model_name='headerfield',
            name='tc',
            field=models.ForeignKey(on_delete=True, to='apimanager.RestApiTestCase'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='tc',
            field=models.ForeignKey(on_delete=True, to='apimanager.RestApiTestCase'),
        ),
    ]
