# Generated by Django 2.0.4 on 2018-04-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restapitestcase',
            name='last_run_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restapitestcase',
            name='last_run_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='data_type',
            field=models.CharField(choices=[('int', 'int'), ('str', 'string'), ('boolean', 'boolean'), ('float', 'float')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restapitestcase',
            name='data_type',
            field=models.CharField(default='JSON', max_length=200),
        ),
        migrations.AlterField(
            model_name='validate',
            name='data_type',
            field=models.CharField(choices=[('int', 'int'), ('str', 'string'), ('boolean', 'boolean'), ('float', 'float')], max_length=20),
        ),
    ]
