# Generated by Django 2.0.4 on 2018-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0002_auto_20180417_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='data_type',
            field=models.CharField(choices=[('int', 'int'), ('str', 'string'), ('boolean', 'boolean'), ('float', 'float'), ('jinja2', 'jinja2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restapitestcase',
            name='data_type',
            field=models.CharField(choices=[('DATA', 'DATA'), ('JSON', 'JSON')], default='JSON', max_length=200),
        ),
    ]
