# Generated by Django 2.0.4 on 2018-04-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0003_auto_20180419_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='host',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
