# Generated by Django 2.0.4 on 2018-04-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0004_project_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_wait',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='project',
            name='min_wait',
            field=models.IntegerField(default=1000),
        ),
    ]
