# Generated by Django 2.0.4 on 2018-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0005_auto_20180419_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='restapitestcase',
            name='response_data_type',
            field=models.CharField(choices=[('DATA', 'DATA'), ('JSON', 'JSON')], default='JSON', max_length=200),
        ),
        migrations.AlterField(
            model_name='restapitestcase',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
