# Generated by Django 2.0.4 on 2018-04-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0007_auto_20180426_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfield',
            name='data_type',
            field=models.CharField(choices=[('int', 'int'), ('str', 'string'), ('boolean', 'boolean'), ('float', 'float'), ('jinja2', 'jinja2')], default=str, max_length=20),
            preserve_default=False,
        ),
    ]
